security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        db_provider:
            id: app.user_provider

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
